---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: boilest-manager
  labels:
    app: boilest-manager
    boilest: manager
spec:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: boilest-manager
  template:
    metadata:
      labels:
        app: boilest-manager
    spec:
      containers:
        - name: boilest-manager
          image: ghcr.io/goingoffroading/boilest-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
            - containerPort: 5555

---
  apiVersion: v1
  kind: Service
  metadata:
    name: boilest-manager
  spec:
    ports:
      - name: flask
        protocol: TCP
        port: 5000
        nodePort: 31500
    selector:
      app: boilest-manager
    type: NodePort

---
  apiVersion: v1
  kind: Service
  metadata:
    name: plex
  spec:
    ports:
      - name: flower
        protocol: TCP
        port: 5555
        nodePort: 31555
    selector:
      app: boilest-manager
    type: NodePort
